### ISSUE TITLE
'configmaps "es-config" not found' and ' failed to "StartContainer"'

### ISSUE THREAD

**Issue by trahloff** [kayrus/elk-kubernetes#16]
On a k8s apiserver v1.5.6 the deployment fails:

![elk_error](https://user-images.githubusercontent.com/16914641/30043379-a2d79450-91bc-11e7-8743-7b9a6bde74fa.png)

Log for kubernetes-event-printer:

`2017-09-05T02:58:52.468020417Z parse error: Invalid numeric literal at line 1, column 10`

Log for es-client:

```
2017-09-05T03:03:38.559340597Z 	... 11 more
2017-09-05T03:03:38.635423286Z [2017-09-05 03:03:38,635][WARN ][io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider] [es-client-4269868645-wvs63] Exception caught during discovery: An error has occurred.
2017-09-05T03:03:38.635448602Z io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
2017-09-05T03:03:38.635454790Z 	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:57)
2017-09-05T03:03:38.635460247Z 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:125)
2017-09-05T03:03:38.635465487Z 	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:35)
2017-09-05T03:03:38.635470618Z 	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.readNodes(KubernetesUnicastHostsProvider.java:112)
2017-09-05T03:03:38.635475447Z 	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.lambda$buildDynamicNodes$0(KubernetesUnicastHostsProvider.java:80)
2017-09-05T03:03:38.635480503Z 	at java.security.AccessController.doPrivileged(Native Method)
2017-09-05T03:03:38.635485257Z 	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:79)
2017-09-05T03:03:38.635490428Z 	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:335)
2017-09-05T03:03:38.635495242Z 	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.ping(UnicastZenPing.java:240)
2017-09-05T03:03:38.635500403Z 	at org.elasticsearch.discovery.zen.ping.ZenPingService.ping(ZenPingService.java:106)
2017-09-05T03:03:38.635505279Z 	at org.elasticsearch.discovery.zen.ping.ZenPingService.pingAndWait(ZenPingService.java:84)
2017-09-05T03:03:38.635510217Z 	at org.elasticsearch.discovery.zen.ZenDiscovery.findMaster(ZenDiscovery.java:945)
2017-09-05T03:03:38.635517456Z 	at org.elasticsearch.discovery.zen.ZenDiscovery.innerJoinCluster(ZenDiscovery.java:360)
2017-09-05T03:03:38.635522390Z 	at org.elasticsearch.discovery.zen.ZenDiscovery.access$4400(ZenDiscovery.java:96)
2017-09-05T03:03:38.635527148Z 	at org.elasticsearch.discovery.zen.ZenDiscovery$JoinThreadControl$1.run(ZenDiscovery.java:1296)
2017-09-05T03:03:38.635545025Z 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
2017-09-05T03:03:38.635550558Z 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
2017-09-05T03:03:38.635555480Z 	at java.lang.Thread.run(Thread.java:745)
2017-09-05T03:03:38.635562181Z Caused by: javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
2017-09-05T03:03:38.635567196Z     certificate: sha1/KROIINnUlQ2e96AR0sQBvJJTyu4=
2017-09-05T03:03:38.635571908Z     DN: CN=10.10.10.1
2017-09-05T03:03:38.635576527Z     subjectAltNames: [10.10.10.1, 10.176.215.15, 169.46.7.238]
2017-09-05T03:03:38.635581169Z 	at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:197)
2017-09-05T03:03:38.635586013Z 	at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
2017-09-05T03:03:38.635590714Z 	at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
2017-09-05T03:03:38.635595466Z 	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
2017-09-05T03:03:38.635600230Z 	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2017-09-05T03:03:38.635604990Z 	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2017-09-05T03:03:38.635609849Z 	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2017-09-05T03:03:38.635614624Z 	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2017-09-05T03:03:38.635619637Z 	at com.squareup.okhttp.Call.getResponse(Call.java:286)
2017-09-05T03:03:38.635624479Z 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
2017-09-05T03:03:38.635629340Z 	at io.fabric8.kubernetes.client.utils.HttpClientUtils$3.intercept(HttpClientUtils.java:110)
2017-09-05T03:03:38.635634086Z 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
2017-09-05T03:03:38.635638770Z 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
2017-09-05T03:03:38.635643513Z 	at com.squareup.okhttp.Call.execute(Call.java:80)
2017-09-05T03:03:38.635648141Z 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:210)
2017-09-05T03:03:38.635652811Z 	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:205)
2017-09-05T03:03:38.635657558Z 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:510)
2017-09-05T03:03:38.635662171Z 	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:118)
2017-09-05T03:03:38.635666876Z 	... 16 more
```

**Comment by sabretus** [comment]
Same issue here, Kubernetes 1.7.2, no custom parameters

I have tried export NETWORK_HOST=0.0.0.0 but still got this in logs:

```
Exception in thread "main" java.lang.IllegalArgumentException: No up-and-running site-local (private) addresses found, got [name:lo (lo), name:eth0 (eth0)]
```

**Comment by sabretus** [comment]
Setting `network.host` directly in elasticsearch.yml to `0.0.0.0` fixed problem for me, here are more details https://github.com/pires/docker-elasticsearch-kubernetes/issues/5
